### ISSUE TITLE
Video not showing

### ISSUE THREAD

**Issue by msiksnis** [MarkBlythe/instagram-gallery#1]
Anyone knows how to fix so the video posts be shown on mobile as well? It works well on desktop but on mobile (at least on iphone) only the pictures are there and where the video should be it is only a blank spot. I suppose it is fetched but not displayed because on apple settings.

**Comment by MarkBlythe** [comment]
Hi, sorry for the slow reply. Been very busy with work and life in general. I originally only made this module for a website gallery for my parents business and therefore didn't bother testing how videos behaved.

I had some time this weekend so I was able to replicate your issue above, seems iOS is very picky but have published v1.3.1 which I believe fixes your issue somewhat. 

Videos should now work on all decent browsers and mobile, thanks to the usage of `autoPlay`, `muted`, `playsInline` and `controls` props.

Please update the module to `1.3.1` and let me know if it solves your issue.
