### ISSUE TITLE
use it on github pages

### ISSUE THREAD

**Issue by KiaraMaker** [MarkBlythe/instagram-gallery#3]
Is it possible to use instagram-gallery with github pages?
I have a static html website and I would like to publish last images from my instagram feed.

**Comment by MarkBlythe** [comment]
Hi, this module was written as a react component so it can't be used that way out of the box. 

Ultimately this package uses an HTTP request to fetch instagram data and return it as an image gallery so you could possibly create a react app that I believe can be hosted using github pages and use this module in one of the pages.
